#  Regression with Two Predictors {#chapter-4}

```{r, echo = F}
button <-  "position: relative; 
            top: -25px; 
            left: 85%;   
            color: white;
            font-weight: bold;
            background: #4B9CD3;
            border: 1px #3079ED solid;
            box-shadow: inset 0 1px 0 #80B0FB"
```

## An example from ECLS 

Compare two simple regressions with multiple regression
* notice difference coefficients and R-square 

## OLS with two predictors

* Write out the "line"
* Show the coefficients 
* Explain with reference to example

## Interpreting the coefficients

* "Holding constant" (Fox)
* Accounting for intercorrelation (set $r_{12}$ to zero)
* "Statistical control" (Pedhazur; or next time)

## Standardized coefficients

* Show formulas
* Interpretation and cautions

## R-squared (again) 

* What is multiple R
* R-squared with two predictors
  * venn diagram
* Adjusted R-squared [Or move this to chapter 2??]
* Do we need R-squared change yet or save until mode building? 

## Inference 

### Coefficients 

* show and interpret new standard formula

### R-squared

* Show and interpret new F-test
 
## Exercises 

* How much does ATL improve the prediction / explanation of Math Achievement, after considering SES? 

* How well do ATL and SES jointly predict / explain Math Achievement? 
