project:
  type: book

book:
  title: "EDUC 784"
  author: "Peter Halpin"
  date: "1/3/2024"
  cover-image: files/images/interaction.jpg 
  chapters:
    - index.qmd
    - review.qmd

  

bibliography: references.bib

format:
  html:
    theme: cosmo
    highlight-style: github
    code-fold: true
    code-tools: true

  pdf:
    documentclass: scrreprt



