project:
  type: book

book:
  title: "EDUC 784"
  author: "Peter Halpin"
  date: "1/3/2024"
  cover-image: files/images/interaction.jpg 
  chapters:
    - index.qmd
    - ch1_review.qmd
    - ch2_simple_regression.qmd
    - ch3_two_predictors.qmd

bibliography: references.bib

css: style.css

format:
  html:
    theme: cosmo
    highlight-style: github
    code-fold: true
    code-tools: true

  # docx:
  #   toc: true
  #   number-sections: true
  #   highlight-style: github
