<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>EDUC 784 - 6&nbsp; Model building</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ch7_assumption_checking.html" rel="next">
<link href="./ch5_interactions.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ch6_model_building.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Model building</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">EDUC 784</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch1_review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Review</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch2_simple_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Simple regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch3_two_predictors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Two predictors</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch4_categorical_predictors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Categorical predictors</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch5_interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Interactions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch6_model_building.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Model building</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch7_assumption_checking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Assumption checking</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-hierarchical-models-6" id="toc-sec-hierarchical-models-6" class="nav-link active" data-scroll-target="#sec-hierarchical-models-6"><span class="header-section-number">6.1</span> Hierarhical models</a>
  <ul class="collapse">
  <li><a href="#example-of-blocks" id="toc-example-of-blocks" class="nav-link" data-scroll-target="#example-of-blocks"><span class="header-section-number">6.1.1</span> Example of blocks</a></li>
  <li><a href="#nested-models" id="toc-nested-models" class="nav-link" data-scroll-target="#nested-models"><span class="header-section-number">6.1.2</span> Nested models</a></li>
  <li><a href="#some-practical-advice" id="toc-some-practical-advice" class="nav-link" data-scroll-target="#some-practical-advice"><span class="header-section-number">6.1.3</span> Some practical advice</a></li>
  <li><a href="#sec-delta-rsquared-6" id="toc-sec-delta-rsquared-6" class="nav-link" data-scroll-target="#sec-delta-rsquared-6"><span class="header-section-number">6.1.4</span> Delta R-squared</a></li>
  </ul></li>
  <li><a href="#sec-worked-example-6" id="toc-sec-worked-example-6" class="nav-link" data-scroll-target="#sec-worked-example-6"><span class="header-section-number">6.2</span> A worked example</a>
  <ul class="collapse">
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions"><span class="header-section-number">6.2.1</span> Research questions</a></li>
  <li><a href="#data-analysis-plan" id="toc-data-analysis-plan" class="nav-link" data-scroll-target="#data-analysis-plan"><span class="header-section-number">6.2.2</span> Data analysis plan</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">6.2.3</span> Results</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation"><span class="header-section-number">6.2.4</span> Interpretation</a></li>
  </ul></li>
  <li><a href="#sec-too-many-predictors-6" id="toc-sec-too-many-predictors-6" class="nav-link" data-scroll-target="#sec-too-many-predictors-6"><span class="header-section-number">6.3</span> Too many predictors?</a>
  <ul class="collapse">
  <li><a href="#nk" id="toc-nk" class="nav-link" data-scroll-target="#nk"><span class="header-section-number">6.3.1</span> <span class="math inline">\(N/K\)</span></a></li>
  <li><a href="#multicollinearity" id="toc-multicollinearity" class="nav-link" data-scroll-target="#multicollinearity"><span class="header-section-number">6.3.2</span> Multicollinearity</a></li>
  </ul></li>
  <li><a href="#workbook" id="toc-workbook" class="nav-link" data-scroll-target="#workbook"><span class="header-section-number">6.4</span> Workbook</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">6.5</span> Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-chap-6" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Model building</span></span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Up until this point we have considered models with only a handful of predictors. This chapter addresses how to scale up to real-life applications in which we may have many predictors. <a href="#sec-hierarchical-models-6"><span>Section&nbsp;6.1</span></a> discusses the main ideas, <a href="#sec-worked-example-6"><span>Section&nbsp;6.2</span></a> goes through a worked example, and <a href="#sec-too-many-predictors-6"><span>Section&nbsp;6.3</span></a> addresses some technical details. Compared to the previous chapters, there aren’t a lot of mathematical details in this chapter. The focus is on using the techniques of the previous chapters in more realistic research scenarios (i.e., with lots of predictors).</p>
<p>There are two basic approaches to model building with many predictors. A <em>simulataneous</em> model is a single regression model that includes all predictors of interest. When there are many predictors, this is sometimes referred to the “kitchen sink” approach – just put everything in the model (including the kitchen sink). Conceptually, this approach has the advantage that it mitigates omitted variable bias and therefore helps justify the causal interpretation of regression coefficients. However, in practice it can lead to computational problems, especially when highly correlated predictors are included in the model. We discuss this situation in <a href="#sec-too-many-predictors-6"><span>Section&nbsp;6.3</span></a>.</p>
<p><em>Hierarchical</em> model building is an alternative approach in which predictors are added into a model sequentially. A hierarchical approach is most appropriate when subsets of predictors can be grouped together conceputally. To illustrate this idea, let’s considering the following hypothetical example in which we seek to explain Reading Achievement using predictors that can be grouped into student factors and curriculum factors:</p>
<ul>
<li>Student factors
<ul>
<li>age</li>
<li>prior achievement</li>
<li>parental education</li>
<li>SES</li>
</ul></li>
<li>Curriculum factors
<ul>
<li>in-classroom reading (hrs)</li>
<li>peer discussion (hrs)</li>
<li>reading materials (level)</li>
<li>homework (hrs)</li>
</ul></li>
</ul>
<p>The student factors and curriculum factors are called “blocks” of predictors. A block is just a conceptual grouping of one or more predictors. It is up to the researcher to decide what counts as a conceptually meaningful block of predictors. The overall idea is to use your knowledge of your research area to design a regression model that addresses your research questions. This takes some practice. We will see some more examples of blocks of predictors in <a href="#sec-hierarchical-models-6"><span>Section&nbsp;6.1</span></a> and <a href="#sec-worked-example-6"><span>Section&nbsp;6.2</span></a>.</p>
<p>In hierarchical regression, blocks of predictors are added into the model one at a time. The rationale for adding the blocks of predictors sequentially is to isolate the proportion of variance in the outcome (i.e., R-squared) attributable to each block, while controlling for the other block(s). Using our example, we could proceed as follows:</p>
<ul>
<li><p><strong>Step 1</strong>. First we run a regression model with just the student factors. These variables are known to predict Reading Achievement, but they aren’t the types of factors that can be intervened upon via schooling. These types of predictors are often called “control variables”. What counts as a control variable is a largely non-statistical consideration that depends on the research context.</p>
<ul>
<li>After we run the regression model with this first block of predictors, we record the R-squared statistic. We don’t care very much about the value of the regression coefficients at this point, since we know we have left out the curriculum factors.</li>
</ul></li>
<li><p><strong>Step 2</strong>: Next we run a regression model with student factors <em>and</em> the curriculum factors, so that our model now includes all of the predictors. By comparing the the R-squared of the model in this second step (curriculum and student factors) to the R-squared of the model in the first step (only student factors), we can determine how much additional variation in Reading Achievement was explained by the curriculum factors. If the additional variation explained by the curriculum factors is substantial, we can reason that intervening on the curriculum may be a good way to improve Reading Achievement.</p></li>
</ul>
<p>It is important to note the following points about this example:</p>
<ul>
<li><p>The second step in the hierarchical model is the same the simultaneous model – they both include all of the predictors. This is true in general. The final step of a hierarchical model is always the same as the corresponding simultaneous model.</p></li>
<li><p>So, what does the hierarchical model give us that the simultaneous model doesn’t? The change in R-squared attributable to each additional block of predictors, controlling for the previous block(s) of predictors. This “change-in-R-squared” statistic is the main focus of this chapter.</p></li>
<li><p>It is important to distinguish model building from variable selection. Model building is about research-question-driven strategies for partitioning the variation explained by a large number of predictors. Variable selection is about “weeding out” predictors that are not useful. So, in model building, the final model should always include all of the potential predictors, but in variable selection, the final model may include only a subset of the potential predictors.</p></li>
<li><p>Variable selection is an important topic that is the focus of a lot current research in machine learning. There was also a large number of “step-wise” regression procedures used for variable selection in last century, but they didn’t work (i.e., different procedures resulted in different models and there were no good criteria by which to choose amongst them). If you have a research scenario that requires variable selection, this problem is best dealt with through machine learning. If you are interested, check out this resource: <a href="https://glmnet.stanford.edu">https://glmnet.stanford.edu</a> (and feel free to ask questions in class!).</p></li>
<li><p>A note on terminology: In some research areas, “hierarchical” is used to refer to multilevel models (e.g., “hierarchical linear models” in sociology). That is not the usage here. It would make sense to refer to the types of models we are calling “hierarchical” as “step-wise”, but, as mentioned in the previous point, the term “step-wise” already refers to a large number flawed techniques for variable selection. So… here we are.</p></li>
</ul>
<p>One last thing: The overall idea of this chapter is that you should build models that answer your research questions. For concreteness, this chapter discusses the main statistical techniques for model building in the context of hierarchical regression. But, you don’t need to use hierarchical regression – the same techniques can be used in other ways creative ways as well.</p>
<section id="sec-hierarchical-models-6" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="sec-hierarchical-models-6"><span class="header-section-number">6.1</span> Hierarhical models</h2>
<p>The key ideas of hierarchical regression are:</p>
<ol type="1">
<li><p>Partition the predictors into conceptual “blocks”. Each block contains at least one predictor, but they usually contain more than one (e.g., “control variables”, “home factors”). No predictor can be included in more than one block.</p></li>
<li><p>Build a series of regression models in which the blocks are entered into the model sequentially. For this to be <em>hierarchical</em> model building, it is required that each new model in the series includes the blocks from all previous models. So, with three blocks we would have:</p></li>
</ol>
<p><span class="math display">\[
\begin{align}
&amp; \text{Model 1: Block 1} \\
&amp; \text{Model 2: Block 1 + Block 2} \\
&amp; \text{Model 3: Block 1 + Block 2 + Block 3} \\
\end{align}
\]</span></p>
<ol start="3" type="1">
<li><p>Compare the R-squared value of each model to that of the previous model. This allows us to determine whether each new block “adds anything” to the model. To see how this works, denote the R-squared values of our three models as <span class="math inline">\(R^2_1, R^2_2, R^2_3\)</span>, respectively. Then we proceed as follows:</p>
<ul>
<li>Compute <span class="math inline">\(R^2_1\)</span> to evaluate the contribution of Block 1.</li>
<li>Compute <span class="math inline">\(\Delta R^2_{21} = R^2_2 - R^2_1\)</span> to evaluate contribution of Block 2, controlling for Block 1</li>
<li>Compute <span class="math inline">\(\Delta R^2_{32} = R^2_3 - R^2_2\)</span> to evaluate contribution of Block 3, controlling for Block 1 &amp; 2.</li>
</ul></li>
</ol>
<p>The symbol <span class="math inline">\(\Delta R^2\)</span> is pronounced “delta R-squared.” It always has two subscripts, which denote the two models being compared.</p>
<p>The main advantage of hierarchical modeling is that we partition the total variance explained by all of the predictors into parts contributed uniquely by each block. In particular, it follows from the definition of delta R-squared that:</p>
<p><span class="math display">\[ R^2_3 = R^2_1 + \Delta R^2_{21} + \Delta R^2_{32}. \]</span> This means that the variation explained by all of the predictors together (<span class="math inline">\(R^2_3\)</span>) can be separated into the 3 distinct components that are isolated by using hierarchical approach.</p>
<p>Sometimes we let <span class="math inline">\(R^2_0\)</span> denote a model that contains no predictors (only the intercept). Then <span class="math inline">\(R^2_1\)</span> can be equilvanently written as <span class="math inline">\(\Delta R^2_{10}\)</span>. This makes the notation of the previous equation a bit more consistent:</p>
<p><span class="math display">\[ R^2_3 = \Delta R^2_{10} + \Delta R^2_{21} + \Delta R^2_{32}.\]</span></p>
<p>The above equation shows us that hierarchical modeling building is an approach to partitioning the total variance explained by a set of predictors (here denoted <span class="math inline">\(R^2_3\)</span>) into the variance uniquely attributable to different blocks of predictors (the <span class="math inline">\(\Delta R^2\)</span>s). While there are many other approaches to model building, this equation is what uniquely defines <em>hierarchical</em> model building.</p>
<section id="example-of-blocks" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="example-of-blocks"><span class="header-section-number">6.1.1</span> Example of blocks</h3>
<p>We have already seen some examples of blocks of predictors in the previous chapters. This section highlights two examples.</p>
<ul>
<li><p>Categorical predictors with <span class="math inline">\(C\)</span> categories are represented as blocks of <span class="math inline">\(C-1\)</span> dummy variables. The dummies are conceptually equivalent to a single predictor.</p></li>
<li><p>Interactions are blocks of predictors. Often interactions are entered into a regression model on separate step, after the “main effects” have been entered. Below is an excerpt from a study that illustrates this approac. The study is about equitable access to gifted-and-talented (GT) programs in New York City. In order to apply for GT programs, students need to take a test in Kindergarten. The test is optional and not everyone takes it. The study is mainly interested in whether attending Pre-K increases the probability that a child will take the test, especially for students who have been traditionally underrepresented in GT programs. (cite: Lu &amp; Wienberg (2016). Public Pre-K and Test Taking for the NYC Gifted-and-Talented Programs: Forging a Path to Equity. Educational Researcher, 45, 36-47):</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="files/images/lu_weinberg_quote.png" class="img-fluid figure-img" width="398"></p>
</figure>
</div>
</div>
</div>
<p>More generally, blocks are any subset of predictors about which you want to ask a research question. It can be just one variable, or it can be a collection of conceptually related variables.</p>
<p><strong>Please take a moment to write down one or more examples of a block of variables from your area of research, and I will invite you to share your examples in class.</strong></p>
</section>
<section id="nested-models" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="nested-models"><span class="header-section-number">6.1.2</span> Nested models</h3>
<p>Whatever your blocks are, hiearhical modeling requires they are used to make a sequence of <em>nested models</em>. The idea behind nested models is depicted in <a href="#fig-nested1">Figure&nbsp;<span>6.1</span></a>. In the figure, Model 2 contains <span class="math inline">\(K\)</span> total predictors, and Model 1 contains a subset of those predictors. This relationship is shown by letting the area representing Model 1 be contained by the area representing Model 2. We can think of this like Matryoshka nesting dolls (<a href="https://en.wikipedia.org/wiki/Matryoshka_doll">https://en.wikipedia.org/wiki/Matryoshka_doll</a>). Model 1 is contained within Model 2, in the sense that all of the predictors in Model 1 are also in Model 2.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-nested1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="files/images/nested1.png" class="img-fluid figure-img" width="264"></p>
<figcaption class="figure-caption">Figure&nbsp;6.1: Nested Models</figcaption>
</figure>
</div>
</div>
</div>
<p>A bit more technically: One regression model is nested within another if the former can be obtained by removing some predictors from the latter. Other than the difference in the predictors, it is assumed that the models equivalent (same outcome variable, sample samples, etc.).</p>
<p>The difference between nested and non-nested models is illustrated in <a href="#fig-nested2">Figure&nbsp;<span>6.2</span></a>. The partially overlapping ovals are intended to indicate that the models share some predictors, but each model also has some unique predictors.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-nested2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="files/images/nested2.png" class="img-fluid figure-img" width="588"></p>
<figcaption class="figure-caption">Figure&nbsp;6.2: Nested vs Non-Nested Models</figcaption>
</figure>
</div>
</div>
</div>
<p>As noted in the figure, a hierarchical model is a series of nested regression models. You might be wondering why it is so important for the models to be nested. Part of this is conceptual – the hierarchical approach allows us to partition the total variance explained into parts attributable to different subsets (blocks) of predictors (see <a href="#sec-hierarchical-models-6"><span>Section&nbsp;6.1</span></a>). Nesting is also required to compute statistical tests for the <span class="math inline">\(\Delta R^2\)</span> statistics (more on this in <a href="#sec-delta-rsquared-6"><span>Section&nbsp;6.1.4</span></a>).</p>
<p>In short, we can statistically compare Model 1 and Model 2 in the left hand panel of <a href="#fig-nested2">Figure&nbsp;<span>6.2</span></a>, but not in the right hand panel. (Side note: In the right hand panel, we could compare Model 1 vs Model 3 and Model 2 vs Model 3, but this would not be a hierarchical model because the <span class="math inline">\(\Delta R^2\)</span>s wouldn’t add up to the <span class="math inline">\(R^2\)</span> of Model 3.)</p>
</section>
<section id="some-practical-advice" class="level3" data-number="6.1.3">
<h3 data-number="6.1.3" class="anchored" data-anchor-id="some-practical-advice"><span class="header-section-number">6.1.3</span> Some practical advice</h3>
<p>So far we have discussed hierarchical modeling conceptually, but have not really addressed how to use it in practice. The following advice is paraphrased from the late Jacob Cohen (cite: Cohen, Cohen, West, &amp; Aitken (2003). Applied Multiple Regression Analysis. Mahwah, NJ: Lawrence Earlbaum. Section 5.7.3).</p>
<ul>
<li><p>The hierarchical approach provides an effective strategy of inference if variables are entered into the model according to their relevance to the study.</p></li>
<li><p>The variables that are most central to the study should be entered first, those that are secondarily of interest should be entered second, and those that fall into the category, “I wonder if” or “just in case” should be entered last.</p></li>
<li><p>This principle may be succinctly stated as “least is last.” That is, “when research factors can be ordered as to their centrality, those of least relevance are appraised last in the hierarchy, and their results taken as indicative rather than conclusive”</p></li>
</ul>
<p><a href="#fig-nested3">Figure&nbsp;<span>6.3</span></a> maps Cohen’s strategy onto our diagram for nested models. One addendum to this approach is that “control variables” are usually entered first. These are variables that have been established as important in past research, but are not of central interest to the present study. The rationale for entering them first is that new studies should add something beyond what has been established by past research.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-nested3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="files/images/nested3.png" class="img-fluid figure-img" width="472"></p>
<figcaption class="figure-caption">Figure&nbsp;6.3: Cohen’s ‘Least is Last’ Principle</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="sec-delta-rsquared-6" class="level3" data-number="6.1.4">
<h3 data-number="6.1.4" class="anchored" data-anchor-id="sec-delta-rsquared-6"><span class="header-section-number">6.1.4</span> Delta R-squared</h3>
<p>We have already seen how to compute <span class="math inline">\(\Delta R^2\)</span> – by subtracting the R-squared value of a nested model from that of a nesting model. This is a very widely used way of comparing nested regression models.</p>
<p>When adding predictors into a model one at a time (i.e., blocks with only a single predictor), testing <span class="math inline">\(\Delta R^2\)</span> is equivalent to testing the b-weight of the added predictor. But when adding multiple predictors into a model, <span class="math inline">\(\Delta R^2\)</span> provides important information that is not captured by any of the statistics we have considered so far. It is technically called a multiple semi-partial correlation, but “delta R-squared” or “R-squared change” are widely used terminology.</p>
<p>Statistical inference for <span class="math inline">\(\Delta R^2\)</span> uses the F-test shown below. Let Model 1 be a regression model with <span class="math inline">\(K_1\)</span> predictors that is nested within Model 2, with <span class="math inline">\(K_2 &gt; K_1\)</span> predictors. Define <span class="math inline">\(\Delta R^2 = R^2_2 - R^2_1\)</span> and <span class="math inline">\(\Delta K = K_2 - K_1\)</span>. To test the hypothesis <span class="math inline">\(H_0: \Delta R^2 = 0\)</span> versus <span class="math inline">\(H_A : \Delta R^2 &gt; 0\)</span> we can use the test statistic</p>
<p><span class="math display">\[F = \frac{\Delta R^2 / \Delta K}{(1 - R^2_2) /(N - K_2 - 1)}  \]</span></p>
<p>which has an F-distribution on <span class="math inline">\(\Delta K\)</span> and <span class="math inline">\(N - K_2 - 1\)</span> degrees of freedom, when the null hypothesis true. This test assumes that Model 2 satisfies the linear regression population model (see @sec-population-model-2) and that Model 1 is nested within Model 2.</p>
</section>
</section>
<section id="sec-worked-example-6" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="sec-worked-example-6"><span class="header-section-number">6.2</span> A worked example</h2>
<p>To illustrate hierarchical modeling, let’s use the ECLS data to address whether reading achievement at the beginning of Kindergarten (<code>c1rrscal</code>) is related to SES (<code>wksesl</code>), parental (mother’s and father’s) education (<code>wkmomed</code> and <code>wkdaded</code>, respectively), and attendance in center-based care before K (<code>p1center</code>; pre-K status, for short).</p>
<p>This example is intended to be a realistic illustration of how to use the techniques we have covered up to this point. The sections below can be thought of as excerpts from a research paper, and also shows how to report results in a regression table. But there are some caveats that should be mentioned before starting:</p>
<ul>
<li>We used some tricks from later chapters to deal with non-linearity, and</li>
<li>keep in the mind the subset of ECLS data we are using is not a representative sample and the results should not be assumed to generalize to the general population.</li>
</ul>
<section id="research-questions" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="research-questions"><span class="header-section-number">6.2.1</span> Research questions</h3>
<p>We will address the following research questions.</p>
<ul>
<li><p>RQ1: Does SES predict Reading Achievement upon entry to K?</p></li>
<li><p>RQ2: Does Parental Education (mother’s and father’s) predict Reading Achievement, after controlling for SES?</p></li>
<li><p>RQ3: After controlling for both SES and Parental Education, is Pre-K Status associated with better Reading Achievement in K?</p></li>
<li><p>RQ4: Does the relationship of SES or Parental Education to Reading Achievement change as function of Pre-K Status – in more causal language: does Pre-K participation reduce pre-existing disparities in Reading Achievement upon entry to K?</p></li>
</ul>
</section>
<section id="data-analysis-plan" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="data-analysis-plan"><span class="header-section-number">6.2.2</span> Data analysis plan</h3>
<p>The research questions were addressed via hierarchical regression modeling with the following blocks of predictors.</p>
<ul>
<li>Block 1: <code>wksesl</code><br>
</li>
<li>Block 2: <code>wkmomed</code> and <code>wkdaded</code></li>
<li>Block 3: <code>plcetner</code></li>
<li>Block 4: Interactions between <code>p1center</code> and the other predictors</li>
</ul>
<p>To aid the interpretation of regression coefficients in the presence of interactions, all continuous variables (predictors and outcome) were transformed to z-scores. <code>plcenter</code> was coded as binary indicator for Pre-K status.</p>
<p>The blocks were entered into the model in the indicated order. The RQs were addressed by examining the R-square change (<span class="math inline">\(\Delta R^2\)</span>) for each corresponding block. (In practice, we would also interpret the sign and direction of the significant regression coefficients in the final model, but we will leave that as an exercise.) A significance level of .05 was used for all tests reported in this study.</p>
<p>Preliminary examination of the model residuals indicated violation of the assumption of linearity. To address this, the outcome variable was log-transformed and a quadratic term was added for <code>wksesl</code> (<code>wksesl_sq</code>). These procedures for checking and addressing non-linearity are discussed in the coming chapters.</p>
</section>
<section id="results" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="results"><span class="header-section-number">6.2.3</span> Results</h3>
<p>The F-tests of R-squared change for each block of predictors are reported in <a href="#fig-table1">Figure&nbsp;<span>6.4</span></a>. The results show that block 1 (linear and quadratic trends in SES) explained about 18% of the variance Reading Achievement. While blocks 2 (parental education) and 3 (Pre-K) contributed statistically significant increases in variance explained, the change in R-squared was not large. Block 4 containing the interactions with Pre-K was not statistically significant after controlling for the main effects.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"ECLS2577.RData"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(ecls)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Recode variables</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>p1center <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">-</span> p1center</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>z_c1rrscal <span class="ot">&lt;-</span> <span class="fu">scale</span>(c1rrscal)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>z_wksesl <span class="ot">&lt;-</span> <span class="fu">scale</span>(wksesl)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>z_wksesl_sq <span class="ot">&lt;-</span> z_wksesl<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>z_wkmomed <span class="ot">&lt;-</span> <span class="fu">scale</span>(wkmomed)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>z_wkdaded <span class="ot">&lt;-</span> <span class="fu">scale</span>(wkdaded)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>log_c1rrscal <span class="ot">&lt;-</span> <span class="fu">log</span>(z_c1rrscal <span class="sc">-</span> <span class="fu">min</span>(z_c1rrscal) <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Run models</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># models</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  z_wksesl <span class="sc">+</span> z_wksesl_sq)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  z_wksesl <span class="sc">+</span> z_wksesl_sq <span class="sc">+</span> z_wkmomed <span class="sc">+</span> z_wkdaded)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  z_wksesl <span class="sc">+</span> z_wksesl_sq <span class="sc">+</span> z_wkmomed <span class="sc">+</span> z_wkdaded <span class="sc">+</span> p1center)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>mod4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  (z_wksesl <span class="sc">+</span> z_wksesl_sq <span class="sc">+</span> z_wkmomed <span class="sc">+</span> z_wkdaded)<span class="sc">*</span>p1center)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>R2_1 <span class="ot">&lt;-</span> <span class="fu">summary</span>(mod1)<span class="sc">$</span>r.squared</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>R2_2 <span class="ot">&lt;-</span> <span class="fu">summary</span>(mod2)<span class="sc">$</span>r.squared</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>R2_3 <span class="ot">&lt;-</span> <span class="fu">summary</span>(mod3)<span class="sc">$</span>r.squared</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>R2_4 <span class="ot">&lt;-</span> <span class="fu">summary</span>(mod4)<span class="sc">$</span>r.squared</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>rsquared <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, R2_1, R2_2, R2_3, R2_4)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>delta_rsquared <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, R2_1, R2_2 <span class="sc">-</span> R2_1, R2_3 <span class="sc">-</span> R2_2, R2_4 <span class="sc">-</span> R2_3)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>Models <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"Model "</span>, <span class="dv">0</span><span class="sc">:</span><span class="dv">4</span>)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(delta_rsquared) <span class="ot">&lt;-</span> Models</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Tests of R-square change</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>model_results <span class="ot">&lt;-</span> knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">cbind</span>(<span class="at">Rsquared =</span> rsquared, </span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">Delta.Rsquared =</span> delta_rsquared, </span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">anova</span>(<span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  <span class="dv">1</span>), mod1, mod2, mod3, mod4)),</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>                           <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>model_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="fig-table1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 20%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 4%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Rsquared</th>
<th style="text-align: right;">Delta.Rsquared</th>
<th style="text-align: right;">Res.Df</th>
<th style="text-align: right;">RSS</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Sum of Sq</th>
<th style="text-align: right;">F</th>
<th style="text-align: right;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Model 0</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">2576</td>
<td style="text-align: right;">343.636</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Model 1</td>
<td style="text-align: right;">0.176</td>
<td style="text-align: right;">0.176</td>
<td style="text-align: right;">2574</td>
<td style="text-align: right;">283.114</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">60.522</td>
<td style="text-align: right;">277.886</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Model 2</td>
<td style="text-align: right;">0.179</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">2572</td>
<td style="text-align: right;">282.032</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.083</td>
<td style="text-align: right;">4.970</td>
<td style="text-align: right;">0.007</td>
</tr>
<tr class="even">
<td style="text-align: left;">Model 3</td>
<td style="text-align: right;">0.184</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">2571</td>
<td style="text-align: right;">280.271</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.761</td>
<td style="text-align: right;">16.168</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Model 4</td>
<td style="text-align: right;">0.187</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">2567</td>
<td style="text-align: right;">279.538</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.733</td>
<td style="text-align: right;">1.683</td>
<td style="text-align: right;">0.151</td>
</tr>
</tbody>
</table>
<figcaption class="figure-caption">Figure&nbsp;6.4: R-squared change and F-tests</figcaption>
</figure>
</div>
</div>
<p>Although we didn’t have research hypotheses about the individual predictors, it is often useful to report a table such as the one below to summarize that kind of information. The table was produced using the <code>stargazer</code> package in R and is representative of the usual format for reporting regression output from hierarchical regression models. The values reported for each variable are the regression coefficients, with the standard errors in parenthesis. <strong>Please take a moment to look over the table and write down any questions you have about its interpretation</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="files/images/stargazer.png" class="img-fluid figure-img" width="677"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation" class="level3" data-number="6.2.4">
<h3 data-number="6.2.4" class="anchored" data-anchor-id="interpretation"><span class="header-section-number">6.2.4</span> Interpretation</h3>
<p>The focus of this section is on the interpretation of the <span class="math inline">\(\Delta R^2\)</span> statistics and their significance. In practice, we would also interpret the sign and direction of the significant regression coefficients in the final model. As noted above, the outcome variable was log transformed, but we ignore that detail here. It would usually not be necessary to report results both in a table and inline, but the latter are shown for illustrative purposes (practice, practice, practice!).</p>
<ul>
<li><p>RQ1: SES had significant linear and quadratic relationships with Reading Achievement. Together, both predictors explained about 17.6% of the variance in Reading Achievement (<span class="math inline">\(R^2 = .176, F(2, 2574) = 275.12, p &lt; .001)\)</span>.</p></li>
<li><p>RQ2: After controlling for SES, Parental Education explained a small but statistically significant proportion of the variance in Reading Achievement (<span class="math inline">\(\Delta R^2 = .003, F(2, 2572) = 4.94, p = .007\)</span>),</p></li>
<li><p>RQ3: After controlling for SES and Parental Education, Pre-K status explained an additional .5% of the variation in reading achievement (<span class="math inline">\(\Delta R^2 = .005, F(1, 2571) = 16.15, p &lt; .001\)</span>).</p></li>
<li><p>RQ4: There was mixed evidence about the interactions between Pre-K Status and the other predictors. The F-test of R-squared change indicated that the interaction terms did not explain a significant amount of variation in reading (<span class="math inline">\(\Delta R^2 = .002, F(4, 2567) = 1.68, p = .15\)</span>). However, the interaction with paternal education was significant at the .05 level. After re-running Model 4 with only the paternal education interaction, it was found that this effect was not significant at the .05 level (<span class="math inline">\(t(2570) = -0.856, p = 0.39\)</span>; see output below). It may be concluded that there were no significant interactions with Pre-K status.</p></li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>mod4A <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  z_wksesl <span class="sc">+</span> z_wksesl_sq <span class="sc">+</span> z_wkmomed <span class="sc">+</span> z_wkdaded<span class="sc">*</span>p1center)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod4A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_c1rrscal ~ z_wksesl + z_wksesl_sq + z_wkmomed + 
    z_wkdaded * p1center)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.88751 -0.23151 -0.00025  0.20858  1.34884 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         0.795829   0.015160  52.495  &lt; 2e-16 ***
z_wksesl            0.115158   0.016322   7.056  2.2e-12 ***
z_wksesl_sq        -0.019645   0.005306  -3.702 0.000218 ***
z_wkmomed           0.018424   0.011174   1.649 0.099327 .  
z_wkdaded           0.042770   0.017016   2.513 0.012016 *  
p1center            0.060274   0.016163   3.729 0.000196 ***
z_wkdaded:p1center -0.014023   0.016373  -0.856 0.391830    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3302 on 2570 degrees of freedom
Multiple R-squared:  0.1846,    Adjusted R-squared:  0.1827 
F-statistic: 96.99 on 6 and 2570 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>In summary, it was found that SES and Parental Education were significant predictors of children’s Reading Achievement upon entry to Kindergarten, indicating that pre-existing disparities in reading due to economic factors are apparent at even this very early age. Attendance in Pre-K explained an additional .5% of variance in Reading Achievement and was associated with increased Reading Achievement; however, there was no evidence that participation in Pre-K reduced pre-existing disparities in Reading Achievement associated with the economic factors (i.e., there were no interactions between Pre-K participation and the economic factors).</p>
</section>
</section>
<section id="sec-too-many-predictors-6" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="sec-too-many-predictors-6"><span class="header-section-number">6.3</span> Too many predictors?</h2>
<p>What is better: more predictors or fewer? While there is no definitive answer to this question, there are two points that we should keep in mind when adding predictors into a model:</p>
<ul>
<li><p>The ratio of sample size to number of predictors: <span class="math inline">\(N / K\)</span>.</p></li>
<li><p>The correlation among the predictors (AKA multicollinearity).</p></li>
</ul>
<p>In order to understand the effect of these factors in multiple regression, its helpful to refer to the formula for the standard error of a regression coefficient (from <a href="ch3_two_predictors.html#sec-inference-for-coeffecients-3"><span>Section&nbsp;3.7.1</span></a>), which is presented again below:</p>
<p><span class="math display">\[
SE({b_k}) = \frac{s_Y}{s_k} \sqrt{\frac{1 - R^2}{N - K - 1}} \times \sqrt{\frac{1}{1 - R_k^2}}.
\]</span></p>
<p>Recall that <span class="math inline">\(s\)</span> denotes standard deviations and that <span class="math inline">\(R_k^2\)</span> is the R-squared from the regression of the <span class="math inline">\(k\)</span>-th predictor on the remaining <span class="math inline">\(K-1\)</span> predictors.</p>
<section id="nk" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="nk"><span class="header-section-number">6.3.1</span> <span class="math inline">\(N/K\)</span></h3>
<p>We can see from the equation for <span class="math inline">\(SE({b_k})\)</span> that increasing the number of predictors leads the term <span class="math inline">\(N-K-1\)</span> to get smaller. Consequently, the ratio</p>
<p><span class="math display">\[ {\frac{1 - R^2}{N - K - 1}} \]</span></p>
<p>will get larger (and hence the standard error will get larger) if the increase in the number of predictors is not compensated by an increase in <span class="math inline">\(R^2.\)</span> In other words, predictors that do not add explanatory power to the model (i.e., do not increase R-squared) will lead to reduced precision for all of the regression coefficients.</p>
<p>So long as <span class="math inline">\(N &gt;&gt; K\)</span>, the effect of the number of predictors is negligible. But when the number of predictors gets close to the sample size, the estimates of the regression coefficients can become very imprecise. Many seek “rules of thumb” for the ratio of observations to predictors. This is just a complicated way of asking how large the sample size needs to be, and the correct answer to that question is provided by power analysis (<a href="ch2_simple_regression.html#sec-power-2"><span>Section&nbsp;2.8</span></a>). That said, if <span class="math inline">\(N/K &lt; 30\)</span>-ish you should start probably worrying about the number of predictors in your model.</p>
</section>
<section id="multicollinearity" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="multicollinearity"><span class="header-section-number">6.3.2</span> Multicollinearity</h3>
<p>Regardless of sample size, when a predictor is highly correlated with the other predictors, its precision is negatively affected via the term <span class="math inline">\(R^2_k\)</span>. When <span class="math inline">\(R^2_k = 1\)</span> the situation is called multicollinearity. Note that multicollinearity can occur even if none of the pairwise correlations among the predictors is large – it has to do with the relation between predictor <span class="math inline">\(k\)</span> and <em>all</em> of the other predictors, which is why it is called <em>multi</em>collinearity.</p>
<p>The term <span class="math inline">\(1 - R_k^2\)</span> is called the <em>tolerance</em> and its reciprocal is called the variance inflation factor (VIF).</p>
<p><span class="math display">\[ VIF = \frac{1}{1 - R_k^2} \]</span></p>
<p>Note that <span class="math inline">\(\sqrt{VIF}\)</span> appears in formula for the standard error of the regression coefficient.</p>
<p>Some examples of how to interpret the <span class="math inline">\(VIF\)</span> are provided below:</p>
<ul>
<li><p>If <span class="math inline">\(VIF = 5\)</span>, the estimated regression coefficient is 5 times less precise than it would be without multicollinearity.</p></li>
<li><p>If <span class="math inline">\(VIF = 10\)</span>, the estimated regression coefficient is 10 times less precise than it would be without multicollinearity.</p></li>
<li><p>If <span class="math inline">\(VIF &gt; 10\)</span>, it is a good idea to reconsider whether the predictor needs to be recoded or omitted from the model.</p></li>
</ul>
<p>In general, it is a good practice to check VIF as part of model diagnostics, which is the topic of the next chapter. For our example, the VIF statistics for Model 3 and Model 4 are reported below.</p>
<p>For Model 3:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("car")</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(mod3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   z_wksesl z_wksesl_sq   z_wkmomed   z_wkdaded    p1center 
   6.290370    1.206007    2.950358    3.377283    1.053738 </code></pre>
</div>
</div>
<p>For Model 4:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(mod4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>there are higher-order terms (interactions) in this model
consider setting type = 'predictor'; see ?vif</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>            z_wksesl          z_wksesl_sq            z_wkmomed 
           28.157965             6.447179            12.799652 
           z_wkdaded             p1center    z_wksesl:p1center 
           13.816244             1.812096            28.320202 
z_wksesl_sq:p1center   z_wkmomed:p1center   z_wkdaded:p1center 
            7.562264            12.516708            14.011576 </code></pre>
</div>
</div>
<p>We can see that including the interactions led to a high degree of multicollinearity for some of the regression coefficients in the model. Based on this information, as well as the non-significant <span class="math inline">\(\Delta R^2\)</span> for the interaction block, it would be advisable to focus our interpretation on Model 3 rather than Model 4.</p>
</section>
</section>
<section id="workbook" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="workbook"><span class="header-section-number">6.4</span> Workbook</h2>
<p>This section collects the questions asked in this chapter. There aren’t many, we will mainly be focussed on going through the worked example during class time.</p>
<p><a href="#sec-hierarchical-models-6"><span>Section&nbsp;6.1</span></a></p>
<p>Please take a moment to write down one or more examples of a block of variables from your area of research, and I will invite you to share your examples in class.</p>
<p><a href="#sec-worked-example-6"><span>Section&nbsp;6.2</span></a></p>
<ul>
<li>Look over the tables below and write down any questions you have about their interpretation or the write up provided in <a href="#sec-worked-example-6"><span>Section&nbsp;6.2</span></a>.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 20%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 4%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Rsquared</th>
<th style="text-align: right;">Delta.Rsquared</th>
<th style="text-align: right;">Res.Df</th>
<th style="text-align: right;">RSS</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Sum of Sq</th>
<th style="text-align: right;">F</th>
<th style="text-align: right;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Model 0</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">2576</td>
<td style="text-align: right;">343.636</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Model 1</td>
<td style="text-align: right;">0.176</td>
<td style="text-align: right;">0.176</td>
<td style="text-align: right;">2574</td>
<td style="text-align: right;">283.114</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">60.522</td>
<td style="text-align: right;">277.886</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Model 2</td>
<td style="text-align: right;">0.179</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">2572</td>
<td style="text-align: right;">282.032</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.083</td>
<td style="text-align: right;">4.970</td>
<td style="text-align: right;">0.007</td>
</tr>
<tr class="even">
<td style="text-align: left;">Model 3</td>
<td style="text-align: right;">0.184</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">2571</td>
<td style="text-align: right;">280.271</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.761</td>
<td style="text-align: right;">16.168</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Model 4</td>
<td style="text-align: right;">0.187</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">2567</td>
<td style="text-align: right;">279.538</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.733</td>
<td style="text-align: right;">1.683</td>
<td style="text-align: right;">0.151</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="files/images/stargazer.png" class="img-fluid figure-img" width="677"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="exercises" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="exercises"><span class="header-section-number">6.5</span> Exercises</h2>
<p>The exercises reproduce the worked example in <a href="#sec-worked-example-6"><span>Section&nbsp;6.2</span></a>. We will go through this material in class together, so you don’t need to work on it before class (but you can if you want.)</p>
<p>Before staring this section, you may find it useful to scroll to the top of the page, click on the “&lt;/&gt; Code” menu, and select “Show All Code.”</p>
<p>First we set up the variables</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean up env. and load data</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co">#rm(list = ls())</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co">#load("ECLS2577.RData")</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co">#attach(ecls)</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Recode variables</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>p1center <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">-</span> p1center</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>z_c1rrscal <span class="ot">&lt;-</span> <span class="fu">scale</span>(c1rrscal)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>z_wksesl <span class="ot">&lt;-</span> <span class="fu">scale</span>(wksesl)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>z_wksesl_sq <span class="ot">&lt;-</span> z_wksesl<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>z_wkmomed <span class="ot">&lt;-</span> <span class="fu">scale</span>(wkmomed)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>z_wkdaded <span class="ot">&lt;-</span> <span class="fu">scale</span>(wkdaded)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>log_c1rrscal <span class="ot">&lt;-</span> <span class="fu">log</span>(z_c1rrscal <span class="sc">-</span> <span class="fu">min</span>(z_c1rrscal) <span class="sc">+</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Next, run the models.</p>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run models</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  z_wksesl <span class="sc">+</span> z_wksesl_sq)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  z_wksesl <span class="sc">+</span> z_wksesl_sq <span class="sc">+</span> z_wkmomed <span class="sc">+</span> z_wkdaded)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  z_wksesl <span class="sc">+</span> z_wksesl_sq <span class="sc">+</span> z_wkmomed <span class="sc">+</span> z_wkdaded <span class="sc">+</span> p1center)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Note the syntax here for interacting one variable with many</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>mod4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  (z_wksesl <span class="sc">+</span> z_wksesl_sq <span class="sc">+</span> z_wkmomed <span class="sc">+</span> z_wkdaded)<span class="sc">*</span>p1center)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression table -- will discuss this in class</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co"># stargazer::stargazer(mod1, mod2, mod3, mod4, type = 'html', omit = "Constant")</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"files/images/stargazer.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<p><img src="files/images/stargazer.png" class="img-fluid" width="677"></p>
<p>The <code>stargazer</code> table doesn’t format nicely in markdown, it is attached as a screen shot instead. We will go through some different types of output with stargazer in class. You must install the <code>stargazer</code> package for the code to work.</p>
<p>The above table reports the <span class="math inline">\(R^2\)</span> for each model but does not provide the <span class="math inline">\(\Delta R^2\)</span> statistics or the corresponding F-tests. The <span class="math inline">\(\Delta R^2\)</span> statistics require some additional processing:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get R-squared </span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>R2_1 <span class="ot">&lt;-</span> <span class="fu">summary</span>(mod1)<span class="sc">$</span>r.squared</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>R2_2 <span class="ot">&lt;-</span> <span class="fu">summary</span>(mod2)<span class="sc">$</span>r.squared</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>R2_3 <span class="ot">&lt;-</span> <span class="fu">summary</span>(mod3)<span class="sc">$</span>r.squared</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>R2_4 <span class="ot">&lt;-</span> <span class="fu">summary</span>(mod4)<span class="sc">$</span>r.squared</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>rsquared <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, R2_1, R2_2, R2_3, R2_4)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute R-squared change</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>delta_rsquared <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, R2_1, R2_2 <span class="sc">-</span> R2_1, R2_3 <span class="sc">-</span> R2_2, R2_4 <span class="sc">-</span> R2_3)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up for pretty printing</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="at">Rsquared =</span> rsquared, </span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Delta.Rsquared =</span> delta_rsquared, </span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">anova</span>(<span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  <span class="dv">1</span>), mod1, mod2, mod3, mod4))</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>             </span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(results, <span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 13%">
<col style="width: 22%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 4%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Rsquared</th>
<th style="text-align: right;">Delta.Rsquared</th>
<th style="text-align: right;">Res.Df</th>
<th style="text-align: right;">RSS</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Sum of Sq</th>
<th style="text-align: right;">F</th>
<th style="text-align: right;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">2576</td>
<td style="text-align: right;">343.636</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.176</td>
<td style="text-align: right;">0.176</td>
<td style="text-align: right;">2574</td>
<td style="text-align: right;">283.114</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">60.522</td>
<td style="text-align: right;">277.886</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.179</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">2572</td>
<td style="text-align: right;">282.032</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.083</td>
<td style="text-align: right;">4.970</td>
<td style="text-align: right;">0.007</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.184</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">2571</td>
<td style="text-align: right;">280.271</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.761</td>
<td style="text-align: right;">16.168</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.187</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">2567</td>
<td style="text-align: right;">279.538</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.733</td>
<td style="text-align: right;">1.683</td>
<td style="text-align: right;">0.151</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The variance inflation factors for Model 3 and Model 4 are obtained use the <code>vif</code> function of the <code>car</code> package (you must install the <code>car</code> package for this code to work).</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.pacakges("car")</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(mod3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   z_wksesl z_wksesl_sq   z_wkmomed   z_wkdaded    p1center 
   6.290370    1.206007    2.950358    3.377283    1.053738 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(mod4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>there are higher-order terms (interactions) in this model
consider setting type = 'predictor'; see ?vif</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>            z_wksesl          z_wksesl_sq            z_wkmomed 
           60.867975            12.682305            28.145377 
           z_wkdaded             p1center    z_wksesl:p1center 
           31.720745             1.812096            59.296155 
z_wksesl_sq:p1center   z_wkmomed:p1center   z_wkdaded:p1center 
           12.217023            28.440378            30.766199 </code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># clean up</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(ecls)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./ch5_interactions.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Interactions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ch7_assumption_checking.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Assumption checking</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb18" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="an">fold:</span><span class="co"> true</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="an">editor:</span><span class="co"> </span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co">  markdown: </span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co">    wrap: 72</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="fu"># Model building {#sec-chap-6}</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>Up until this point we have considered models with only a handful of predictors. This chapter addresses how to scale up to real-life applications in which we may have many predictors. @sec-hierarchical-models-6 discusses the main ideas, @sec-worked-example-6 goes through a worked example, and @sec-too-many-predictors-6 addresses some technical details. Compared to the previous chapters, there aren't a lot of mathematical details in this chapter. The focus is on using the techniques of the previous chapters in more realistic research scenarios (i.e., with lots of predictors). </span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>There are two basic approaches to model building with many predictors. A *simulataneous* model is a single regression model that includes all predictors of interest. When there are many predictors, this is sometimes referred to the "kitchen sink" approach -- just put everything in the model (including the kitchen sink). Conceptually, this approach has the advantage that it mitigates  omitted variable bias and therefore helps justify the causal interpretation of regression coefficients. However, in practice it can lead to computational problems, especially when highly correlated predictors are included in the model. We discuss this situation in @sec-too-many-predictors-6.</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>*Hierarchical* model building is an alternative approach in which predictors are added into a model sequentially. A hierarchical approach is most appropriate when subsets of predictors can be grouped together conceputally. To illustrate this idea, let's considering the following hypothetical example in which we seek to explain Reading Achievement using predictors that can be grouped into student factors and curriculum factors:</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Student factors</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>age</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>prior achievement</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>parental education</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>SES</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Curriculum factors</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>in-classroom reading (hrs)</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>peer discussion (hrs)</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>reading materials (level)</span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>homework (hrs)</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>The student factors and curriculum factors are called "blocks" of predictors. A block is just a conceptual grouping of one or more predictors. It is up to the researcher to decide what counts as a conceptually meaningful block of predictors. The overall idea is to use your knowledge of your research area to design a regression model that addresses your research questions. This takes some practice. We will see some more examples of blocks of predictors in @sec-hierarchical-models-6 and @sec-worked-example-6.</span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>In hierarchical regression, blocks of predictors are added into the model one at a time. The rationale for adding the blocks of predictors sequentially is to isolate the proportion of variance in the outcome (i.e., R-squared) attributable to each block, while controlling for the other block(s). Using our example, we could proceed as follows: </span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Step 1**. First we run a regression model with just the student factors. These variables are known to predict Reading Achievement, but they aren't the types of factors that can be intervened upon via schooling. These types of predictors are often called "control variables". What counts as a control variable is a largely non-statistical consideration that depends on the research context. </span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>After we run the regression model with this first block of predictors, we record the R-squared statistic. We don't care very much about the value of the regression coefficients at this point, since we know we have left out the curriculum factors. </span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Step 2**: Next we run a regression model with student factors *and* the curriculum factors, so that our model now includes all of the predictors. By comparing the the R-squared of the model in this second step (curriculum and student factors) to the R-squared of the model in the first step (only student factors), we can determine how much additional variation in Reading Achievement was explained by the curriculum factors. If the additional variation explained by the curriculum factors is substantial, we can reason that intervening on the curriculum may be a good way to improve Reading Achievement. </span>
<span id="cb18-36"><a href="#cb18-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-37"><a href="#cb18-37" aria-hidden="true" tabindex="-1"></a>It is important to note the following points about this example: </span>
<span id="cb18-38"><a href="#cb18-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-39"><a href="#cb18-39" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>The second step in the hierarchical model is the same the simultaneous model -- they both include all of the predictors. This is true in general. The final step of a hierarchical model is always the same as the corresponding simultaneous model. </span>
<span id="cb18-40"><a href="#cb18-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-41"><a href="#cb18-41" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>So, what does the hierarchical model give us that the simultaneous model doesn't? The change in R-squared attributable to each additional block of predictors, controlling for the previous block(s) of predictors. This "change-in-R-squared" statistic is the main focus of this chapter.</span>
<span id="cb18-42"><a href="#cb18-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-43"><a href="#cb18-43" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>It is important to distinguish model building from variable selection. Model building is about research-question-driven strategies for partitioning the variation explained by a large number of predictors. Variable selection is about "weeding out" predictors that are not useful. So, in model building, the final model should always include all of the potential predictors, but in variable selection, the final model may include only a subset of the potential predictors.</span>
<span id="cb18-44"><a href="#cb18-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-45"><a href="#cb18-45" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Variable selection is an important topic that is the focus of a lot current research in machine learning. There was also a large number of "step-wise" regression procedures used for variable selection in last century, but they didn't work (i.e., different procedures resulted in different models and there were no good criteria by which to choose amongst them). If you have a research scenario that requires variable selection, this problem is best dealt with through machine learning. If you are interested, check out this resource: <span class="co">[</span><span class="ot">https://glmnet.stanford.edu</span><span class="co">](https://glmnet.stanford.edu)</span> (and feel free to ask questions in class!).  </span>
<span id="cb18-46"><a href="#cb18-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-47"><a href="#cb18-47" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>A note on terminology: In some research areas, "hierarchical" is used to refer to multilevel models (e.g., "hierarchical linear models" in sociology). That is not the usage here. It would make sense to refer to the types of models we are calling "hierarchical" as "step-wise", but, as mentioned in the previous point, the term "step-wise" already refers to a large number flawed techniques for variable selection.  So... here we are.   </span>
<span id="cb18-48"><a href="#cb18-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-49"><a href="#cb18-49" aria-hidden="true" tabindex="-1"></a>One last thing: The overall idea of this chapter is that you should build models that answer your research questions. For concreteness, this chapter discusses the main statistical techniques for model building in the context of hierarchical regression. But, you don't need to use hierarchical regression -- the same techniques can be used in other ways creative ways as well. </span>
<span id="cb18-50"><a href="#cb18-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-51"><a href="#cb18-51" aria-hidden="true" tabindex="-1"></a><span class="fu">## Hierarhical models {#sec-hierarchical-models-6}</span></span>
<span id="cb18-52"><a href="#cb18-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-53"><a href="#cb18-53" aria-hidden="true" tabindex="-1"></a>The key ideas of hierarchical regression are:  </span>
<span id="cb18-54"><a href="#cb18-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-55"><a href="#cb18-55" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Partition the predictors into conceptual "blocks". Each block contains at least one predictor, but they usually contain more than one (e.g., "control variables", "home factors"). No predictor can be included in more than one block. </span>
<span id="cb18-56"><a href="#cb18-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-57"><a href="#cb18-57" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Build a series of regression models in which the blocks are entered into the model sequentially. For this to be *hierarchical* model building, it is required that each new model in the series includes the blocks from all previous models. So, with three blocks we would have:</span>
<span id="cb18-58"><a href="#cb18-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-59"><a href="#cb18-59" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb18-60"><a href="#cb18-60" aria-hidden="true" tabindex="-1"></a>\begin{align}</span>
<span id="cb18-61"><a href="#cb18-61" aria-hidden="true" tabindex="-1"></a>&amp; \text{Model 1: Block 1} <span class="sc">\\</span></span>
<span id="cb18-62"><a href="#cb18-62" aria-hidden="true" tabindex="-1"></a>&amp; \text{Model 2: Block 1 + Block 2} <span class="sc">\\</span></span>
<span id="cb18-63"><a href="#cb18-63" aria-hidden="true" tabindex="-1"></a>&amp; \text{Model 3: Block 1 + Block 2 + Block 3} <span class="sc">\\</span></span>
<span id="cb18-64"><a href="#cb18-64" aria-hidden="true" tabindex="-1"></a>\end{align}</span>
<span id="cb18-65"><a href="#cb18-65" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb18-66"><a href="#cb18-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-67"><a href="#cb18-67" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Compare the R-squared value of each model to that of the previous model. This allows us to determine whether each new block "adds anything" to the model. To see how this works, denote the R-squared values of our three models as $R^2_1, R^2_2, R^2_3$, respectively. Then we proceed as follows:  </span>
<span id="cb18-68"><a href="#cb18-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-69"><a href="#cb18-69" aria-hidden="true" tabindex="-1"></a><span class="ss">    * </span>Compute $R^2_1$ to evaluate the contribution of Block 1.</span>
<span id="cb18-70"><a href="#cb18-70" aria-hidden="true" tabindex="-1"></a><span class="ss">    * </span>Compute $\Delta R^2_{21} = R^2_2 - R^2_1$ to evaluate contribution of Block 2, controlling for Block 1 </span>
<span id="cb18-71"><a href="#cb18-71" aria-hidden="true" tabindex="-1"></a><span class="ss">    * </span>Compute $\Delta R^2_{32} = R^2_3 - R^2_2$ to evaluate contribution of Block 3, controlling for Block 1 &amp; 2. </span>
<span id="cb18-72"><a href="#cb18-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-73"><a href="#cb18-73" aria-hidden="true" tabindex="-1"></a>The symbol $\Delta R^2$ is pronounced "delta R-squared." It always has two subscripts, which denote the two models being compared. </span>
<span id="cb18-74"><a href="#cb18-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-75"><a href="#cb18-75" aria-hidden="true" tabindex="-1"></a>The main advantage of hierarchical modeling is that we partition the total variance explained by all of the predictors into parts contributed uniquely by each block. In particular, it follows from the definition of delta R-squared that:</span>
<span id="cb18-76"><a href="#cb18-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-77"><a href="#cb18-77" aria-hidden="true" tabindex="-1"></a>$$ R^2_3 = R^2_1 + \Delta R^2_{21} + \Delta R^2_{32}. $$</span>
<span id="cb18-78"><a href="#cb18-78" aria-hidden="true" tabindex="-1"></a>This means that the variation explained by all of the predictors together ($R^2_3$) can be separated into the 3 distinct components that are isolated by using  hierarchical approach. </span>
<span id="cb18-79"><a href="#cb18-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-80"><a href="#cb18-80" aria-hidden="true" tabindex="-1"></a>Sometimes we let $R^2_0$ denote a model that contains no predictors (only the intercept). Then $R^2_1$ can be equilvanently written as $\Delta R^2_{10}$. This makes the notation of the previous equation a bit more consistent:</span>
<span id="cb18-81"><a href="#cb18-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-82"><a href="#cb18-82" aria-hidden="true" tabindex="-1"></a>$$ R^2_3 = \Delta R^2_{10} + \Delta R^2_{21} + \Delta R^2_{32}.$$</span>
<span id="cb18-83"><a href="#cb18-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-84"><a href="#cb18-84" aria-hidden="true" tabindex="-1"></a>The above equation shows us that hierarchical modeling building is an approach to partitioning the total variance explained by a set of predictors (here denoted $R^2_3$) into the variance uniquely attributable to different blocks of predictors (the $\Delta R^2$s). While there are many other approaches to model building, this equation is what uniquely defines *hierarchical* model building. </span>
<span id="cb18-85"><a href="#cb18-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-86"><a href="#cb18-86" aria-hidden="true" tabindex="-1"></a><span class="fu">### Example of blocks</span></span>
<span id="cb18-87"><a href="#cb18-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-88"><a href="#cb18-88" aria-hidden="true" tabindex="-1"></a>We have already seen some examples of blocks of predictors in the previous chapters. This section highlights two examples. </span>
<span id="cb18-89"><a href="#cb18-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-90"><a href="#cb18-90" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Categorical predictors with $C$ categories are represented as blocks of $C-1$ dummy variables. The dummies are conceptually equivalent to a single predictor. </span>
<span id="cb18-91"><a href="#cb18-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-92"><a href="#cb18-92" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Interactions are blocks of predictors. Often interactions are entered into a regression model on separate step, after the "main effects" have been entered. Below is an excerpt from a study that illustrates this approac. The study is about equitable access to gifted-and-talented (GT) programs in New York City. In order to apply for GT programs, students need to take a test in Kindergarten. The test is optional and not everyone takes it. The study is mainly interested in whether attending Pre-K increases the probability that a child will take the test, especially for students who have been traditionally underrepresented in GT programs. (cite: Lu &amp; Wienberg (2016). Public Pre-K and Test Taking for the NYC Gifted-and-Talented Programs: Forging a Path to Equity. Educational Researcher, 45, 36-47):  </span>
<span id="cb18-93"><a href="#cb18-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-94"><a href="#cb18-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-95"><a href="#cb18-95" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo = F, fig.align = 'center'}</span></span>
<span id="cb18-96"><a href="#cb18-96" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"files/images/lu_weinberg_quote.png"</span>)</span>
<span id="cb18-97"><a href="#cb18-97" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-98"><a href="#cb18-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-99"><a href="#cb18-99" aria-hidden="true" tabindex="-1"></a>More generally, blocks are any subset of predictors about which you want to ask a research question. It can be just one variable, or it can be a collection of conceptually related variables. </span>
<span id="cb18-100"><a href="#cb18-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-101"><a href="#cb18-101" aria-hidden="true" tabindex="-1"></a>**Please take a moment to write down one or more examples of a block of variables from your area of research, and I will invite you to share your examples in class.**</span>
<span id="cb18-102"><a href="#cb18-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-103"><a href="#cb18-103" aria-hidden="true" tabindex="-1"></a><span class="fu">### Nested models</span></span>
<span id="cb18-104"><a href="#cb18-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-105"><a href="#cb18-105" aria-hidden="true" tabindex="-1"></a>Whatever your blocks are, hiearhical modeling requires they are used to make a sequence of *nested models*. The idea behind nested models is depicted in @fig-nested1. In the figure, Model 2 contains $K$ total predictors, and Model 1 contains a subset of those predictors. This relationship is shown by letting the area representing Model 1 be contained by the area representing Model 2. We can think of this like Matryoshka nesting dolls (<span class="co">[</span><span class="ot">https://en.wikipedia.org/wiki/Matryoshka_doll</span><span class="co">](https://en.wikipedia.org/wiki/Matryoshka_doll)</span>). Model 1 is contained within Model 2, in the sense that all of the predictors in Model 1 are also in Model 2.</span>
<span id="cb18-106"><a href="#cb18-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-107"><a href="#cb18-107" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fig-nested1, fig.cap = "Nested Models", echo = F, fig.align = 'center'}</span></span>
<span id="cb18-108"><a href="#cb18-108" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"files/images/nested1.png"</span>)</span>
<span id="cb18-109"><a href="#cb18-109" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-110"><a href="#cb18-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-111"><a href="#cb18-111" aria-hidden="true" tabindex="-1"></a>A bit more technically: One regression model is nested within another if the former can be obtained by removing some predictors from the latter.  Other than the difference in the predictors, it is assumed that the models equivalent (same outcome variable, sample samples, etc.). </span>
<span id="cb18-112"><a href="#cb18-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-113"><a href="#cb18-113" aria-hidden="true" tabindex="-1"></a>The difference between nested and non-nested models is illustrated in @fig-nested2. The partially overlapping ovals are intended to indicate that the models share some predictors, but each model also has some unique predictors. </span>
<span id="cb18-114"><a href="#cb18-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-115"><a href="#cb18-115" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fig-nested2, echo = F, fig.cap = "Nested vs Non-Nested Models",  fig.align = 'center'}</span></span>
<span id="cb18-116"><a href="#cb18-116" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"files/images/nested2.png"</span>)</span>
<span id="cb18-117"><a href="#cb18-117" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-118"><a href="#cb18-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-119"><a href="#cb18-119" aria-hidden="true" tabindex="-1"></a>As noted in the figure, a hierarchical model is a series of nested regression models. You might be wondering why it is so important for the models to be nested. Part of this is conceptual -- the hierarchical approach allows us to partition the total variance explained into parts attributable to different subsets (blocks) of predictors (see @sec-hierarchical-models-6). Nesting is also required to compute statistical tests for the $\Delta R^2$ statistics (more on this in @sec-delta-rsquared-6). </span>
<span id="cb18-120"><a href="#cb18-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-121"><a href="#cb18-121" aria-hidden="true" tabindex="-1"></a>In short, we can statistically compare Model 1 and Model 2 in the left hand panel of @fig-nested2, but not in the right hand panel. (Side note: In the right hand panel, we could compare Model 1 vs Model 3 and Model 2 vs Model 3,  but this would not be a hierarchical model because the $\Delta R^2$s wouldn't add up to the $R^2$ of Model 3.)</span>
<span id="cb18-122"><a href="#cb18-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-123"><a href="#cb18-123" aria-hidden="true" tabindex="-1"></a><span class="fu">### Some practical advice</span></span>
<span id="cb18-124"><a href="#cb18-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-125"><a href="#cb18-125" aria-hidden="true" tabindex="-1"></a>So far we have discussed hierarchical modeling conceptually, but have not really addressed how to use it in practice. The following advice is paraphrased from the late Jacob Cohen (cite: Cohen, Cohen, West, &amp; Aitken (2003). Applied Multiple Regression Analysis. Mahwah, NJ: Lawrence Earlbaum. Section 5.7.3).   </span>
<span id="cb18-126"><a href="#cb18-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-127"><a href="#cb18-127" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>The hierarchical approach provides an effective strategy of inference if variables are entered into the model according to their relevance to the study. </span>
<span id="cb18-128"><a href="#cb18-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-129"><a href="#cb18-129" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>The variables that are most central to the study should be entered first, those that are secondarily of interest should be entered second, and those that fall into the category, “I wonder if” or “just in case” should be entered last.</span>
<span id="cb18-130"><a href="#cb18-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-131"><a href="#cb18-131" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>This principle may be succinctly stated as “least is last.”  That is, “when research factors can be ordered as to their centrality, those of least relevance are appraised last in the hierarchy, and their results taken as indicative rather than conclusive” </span>
<span id="cb18-132"><a href="#cb18-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-133"><a href="#cb18-133" aria-hidden="true" tabindex="-1"></a>@fig-nested3 maps Cohen's strategy onto our diagram for nested models. One addendum to this approach is that "control variables" are usually entered first. These are variables that have been established as important in past research, but are not of central interest to the present study. The rationale for entering them first is that new studies should add something beyond what has been established by past research. </span>
<span id="cb18-134"><a href="#cb18-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-135"><a href="#cb18-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-136"><a href="#cb18-136" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fig-nested3, fig.cap = "Cohen's 'Least is Last' Principle", echo = F, fig.align = 'center'}</span></span>
<span id="cb18-137"><a href="#cb18-137" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"files/images/nested3.png"</span>)</span>
<span id="cb18-138"><a href="#cb18-138" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-139"><a href="#cb18-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-140"><a href="#cb18-140" aria-hidden="true" tabindex="-1"></a><span class="fu">### Delta R-squared {#sec-delta-rsquared-6}</span></span>
<span id="cb18-141"><a href="#cb18-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-142"><a href="#cb18-142" aria-hidden="true" tabindex="-1"></a>We have already seen how to compute $\Delta R^2$ -- by subtracting the R-squared value of a nested model from that of a nesting model. This is a very widely used way of comparing nested regression models. </span>
<span id="cb18-143"><a href="#cb18-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-144"><a href="#cb18-144" aria-hidden="true" tabindex="-1"></a>When adding predictors into a model one at a time (i.e., blocks with only a single predictor), testing $\Delta R^2$ is equivalent to testing the b-weight of the added predictor. But when adding multiple predictors into a model, $\Delta R^2$ provides important information that is not captured by any of the statistics we have considered so far. It is technically called a multiple semi-partial correlation, but "delta R-squared" or "R-squared change" are widely used terminology. </span>
<span id="cb18-145"><a href="#cb18-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-146"><a href="#cb18-146" aria-hidden="true" tabindex="-1"></a>Statistical inference for $\Delta R^2$ uses the F-test shown below. Let Model 1 be a regression model with $K_1$ predictors that is nested within Model 2, with $K_2 &gt; K_1$ predictors. Define $\Delta R^2 = R^2_2 - R^2_1$ and $\Delta K = K_2 - K_1$. To test the hypothesis $H_0: \Delta R^2 = 0$ versus $H_A : \Delta R^2 &gt; 0$ we can use the test statistic</span>
<span id="cb18-147"><a href="#cb18-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-148"><a href="#cb18-148" aria-hidden="true" tabindex="-1"></a>$$F = \frac{\Delta R^2 / \Delta K}{(1 - R^2_2) /(N - K_2 - 1)}  $$</span>
<span id="cb18-149"><a href="#cb18-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-150"><a href="#cb18-150" aria-hidden="true" tabindex="-1"></a>which has an F-distribution on $\Delta K$ and $N - K_2 - 1$ degrees of freedom, when the null hypothesis true. This test assumes that Model 2 satisfies the linear regression population model (see \@sec-population-model-2) and that Model 1 is nested within Model 2.  </span>
<span id="cb18-151"><a href="#cb18-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-152"><a href="#cb18-152" aria-hidden="true" tabindex="-1"></a><span class="fu">## A worked example {#sec-worked-example-6}</span></span>
<span id="cb18-153"><a href="#cb18-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-154"><a href="#cb18-154" aria-hidden="true" tabindex="-1"></a>To illustrate hierarchical modeling, let's use the ECLS data to address whether reading achievement at the beginning of Kindergarten (<span class="in">`c1rrscal`</span>) is related to SES (<span class="in">`wksesl`</span>), parental (mother's and father's) education (<span class="in">`wkmomed`</span> and <span class="in">`wkdaded`</span>, respectively), and attendance in center-based care before K (<span class="in">`p1center`</span>; pre-K status, for short). </span>
<span id="cb18-155"><a href="#cb18-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-156"><a href="#cb18-156" aria-hidden="true" tabindex="-1"></a>This example is intended to be a realistic illustration of how to use the techniques we have covered up to this point. The sections below can be thought of as excerpts from a research paper, and also shows how to report results in a regression table. But there are some caveats that should be mentioned before starting: </span>
<span id="cb18-157"><a href="#cb18-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-158"><a href="#cb18-158" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>We used some tricks from later chapters to deal with non-linearity, and </span>
<span id="cb18-159"><a href="#cb18-159" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>keep in the mind the subset of ECLS data we are using is not a representative sample and the results should not be assumed to generalize to the general population.  </span>
<span id="cb18-160"><a href="#cb18-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-161"><a href="#cb18-161" aria-hidden="true" tabindex="-1"></a><span class="fu">### Research questions</span></span>
<span id="cb18-162"><a href="#cb18-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-163"><a href="#cb18-163" aria-hidden="true" tabindex="-1"></a>We will address the following research questions. </span>
<span id="cb18-164"><a href="#cb18-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-165"><a href="#cb18-165" aria-hidden="true" tabindex="-1"></a><span class="ss"> * </span>RQ1: Does SES predict Reading Achievement upon entry to K?</span>
<span id="cb18-166"><a href="#cb18-166" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb18-167"><a href="#cb18-167" aria-hidden="true" tabindex="-1"></a><span class="ss"> * </span>RQ2: Does Parental Education (mother's and father's) predict Reading Achievement, after controlling for SES?</span>
<span id="cb18-168"><a href="#cb18-168" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb18-169"><a href="#cb18-169" aria-hidden="true" tabindex="-1"></a><span class="ss"> * </span>RQ3: After controlling for both SES and Parental Education, is Pre-K Status associated with better Reading Achievement in K?</span>
<span id="cb18-170"><a href="#cb18-170" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb18-171"><a href="#cb18-171" aria-hidden="true" tabindex="-1"></a><span class="ss"> * </span>RQ4: Does the relationship of SES or Parental Education to Reading Achievement change as function of Pre-K Status -- in more causal language: does Pre-K participation reduce pre-existing disparities in Reading Achievement upon entry to K?</span>
<span id="cb18-172"><a href="#cb18-172" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb18-173"><a href="#cb18-173" aria-hidden="true" tabindex="-1"></a><span class="fu">### Data analysis plan</span></span>
<span id="cb18-174"><a href="#cb18-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-175"><a href="#cb18-175" aria-hidden="true" tabindex="-1"></a>The research questions were addressed via hierarchical regression modeling with the following blocks of predictors.</span>
<span id="cb18-176"><a href="#cb18-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-177"><a href="#cb18-177" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>Block 1: <span class="in">`wksesl`</span>    </span>
<span id="cb18-178"><a href="#cb18-178" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>Block 2: <span class="in">`wkmomed`</span> and <span class="in">`wkdaded`</span></span>
<span id="cb18-179"><a href="#cb18-179" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>Block 3: <span class="in">`plcetner`</span></span>
<span id="cb18-180"><a href="#cb18-180" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>Block 4: Interactions between <span class="in">`p1center`</span> and the other predictors</span>
<span id="cb18-181"><a href="#cb18-181" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb18-182"><a href="#cb18-182" aria-hidden="true" tabindex="-1"></a>To aid the interpretation of regression coefficients in the presence of interactions, all continuous variables (predictors and outcome) were transformed to z-scores. <span class="in">`plcenter`</span> was coded as binary indicator for Pre-K status.</span>
<span id="cb18-183"><a href="#cb18-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-184"><a href="#cb18-184" aria-hidden="true" tabindex="-1"></a>The blocks were entered into the model in the indicated order. The RQs were addressed by examining the R-square change ($\Delta R^2$) for each corresponding block. (In practice, we would also interpret the sign and direction of the significant regression coefficients in the final model, but we will leave that as an exercise.) A significance level of .05 was used for all tests reported in this study.</span>
<span id="cb18-185"><a href="#cb18-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-186"><a href="#cb18-186" aria-hidden="true" tabindex="-1"></a>Preliminary examination of the model residuals indicated violation of the assumption of linearity. To address this, the outcome variable was log-transformed and a quadratic term was added for <span class="in">`wksesl`</span> (<span class="in">`wksesl_sq`</span>). These procedures for checking and addressing non-linearity are discussed in the coming chapters. </span>
<span id="cb18-187"><a href="#cb18-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-188"><a href="#cb18-188" aria-hidden="true" tabindex="-1"></a><span class="fu">### Results</span></span>
<span id="cb18-189"><a href="#cb18-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-190"><a href="#cb18-190" aria-hidden="true" tabindex="-1"></a>The F-tests of R-squared change for each block of predictors are reported in @fig-table1. The results show that block 1 (linear and quadratic trends in SES) explained about 18% of the variance Reading Achievement. While blocks 2 (parental education) and 3 (Pre-K) contributed statistically significant increases in variance explained, the change in R-squared was not large. Block 4 containing the interactions with Pre-K was not statistically significant after controlling for the main effects.   </span>
<span id="cb18-191"><a href="#cb18-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-192"><a href="#cb18-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-193"><a href="#cb18-193" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, fig-table1, fig.cap= "R-squared change and F-tests"} </span></span>
<span id="cb18-194"><a href="#cb18-194" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"ECLS2577.RData"</span>)</span>
<span id="cb18-195"><a href="#cb18-195" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(ecls)</span>
<span id="cb18-196"><a href="#cb18-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-197"><a href="#cb18-197" aria-hidden="true" tabindex="-1"></a><span class="co"># Recode variables</span></span>
<span id="cb18-198"><a href="#cb18-198" aria-hidden="true" tabindex="-1"></a>p1center <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">-</span> p1center</span>
<span id="cb18-199"><a href="#cb18-199" aria-hidden="true" tabindex="-1"></a>z_c1rrscal <span class="ot">&lt;-</span> <span class="fu">scale</span>(c1rrscal)</span>
<span id="cb18-200"><a href="#cb18-200" aria-hidden="true" tabindex="-1"></a>z_wksesl <span class="ot">&lt;-</span> <span class="fu">scale</span>(wksesl)</span>
<span id="cb18-201"><a href="#cb18-201" aria-hidden="true" tabindex="-1"></a>z_wksesl_sq <span class="ot">&lt;-</span> z_wksesl<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb18-202"><a href="#cb18-202" aria-hidden="true" tabindex="-1"></a>z_wkmomed <span class="ot">&lt;-</span> <span class="fu">scale</span>(wkmomed)</span>
<span id="cb18-203"><a href="#cb18-203" aria-hidden="true" tabindex="-1"></a>z_wkdaded <span class="ot">&lt;-</span> <span class="fu">scale</span>(wkdaded)</span>
<span id="cb18-204"><a href="#cb18-204" aria-hidden="true" tabindex="-1"></a>log_c1rrscal <span class="ot">&lt;-</span> <span class="fu">log</span>(z_c1rrscal <span class="sc">-</span> <span class="fu">min</span>(z_c1rrscal) <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb18-205"><a href="#cb18-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-206"><a href="#cb18-206" aria-hidden="true" tabindex="-1"></a><span class="co"># Run models</span></span>
<span id="cb18-207"><a href="#cb18-207" aria-hidden="true" tabindex="-1"></a><span class="co"># models</span></span>
<span id="cb18-208"><a href="#cb18-208" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  z_wksesl <span class="sc">+</span> z_wksesl_sq)</span>
<span id="cb18-209"><a href="#cb18-209" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  z_wksesl <span class="sc">+</span> z_wksesl_sq <span class="sc">+</span> z_wkmomed <span class="sc">+</span> z_wkdaded)</span>
<span id="cb18-210"><a href="#cb18-210" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  z_wksesl <span class="sc">+</span> z_wksesl_sq <span class="sc">+</span> z_wkmomed <span class="sc">+</span> z_wkdaded <span class="sc">+</span> p1center)</span>
<span id="cb18-211"><a href="#cb18-211" aria-hidden="true" tabindex="-1"></a>mod4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  (z_wksesl <span class="sc">+</span> z_wksesl_sq <span class="sc">+</span> z_wkmomed <span class="sc">+</span> z_wkdaded)<span class="sc">*</span>p1center)</span>
<span id="cb18-212"><a href="#cb18-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-213"><a href="#cb18-213" aria-hidden="true" tabindex="-1"></a>R2_1 <span class="ot">&lt;-</span> <span class="fu">summary</span>(mod1)<span class="sc">$</span>r.squared</span>
<span id="cb18-214"><a href="#cb18-214" aria-hidden="true" tabindex="-1"></a>R2_2 <span class="ot">&lt;-</span> <span class="fu">summary</span>(mod2)<span class="sc">$</span>r.squared</span>
<span id="cb18-215"><a href="#cb18-215" aria-hidden="true" tabindex="-1"></a>R2_3 <span class="ot">&lt;-</span> <span class="fu">summary</span>(mod3)<span class="sc">$</span>r.squared</span>
<span id="cb18-216"><a href="#cb18-216" aria-hidden="true" tabindex="-1"></a>R2_4 <span class="ot">&lt;-</span> <span class="fu">summary</span>(mod4)<span class="sc">$</span>r.squared</span>
<span id="cb18-217"><a href="#cb18-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-218"><a href="#cb18-218" aria-hidden="true" tabindex="-1"></a>rsquared <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, R2_1, R2_2, R2_3, R2_4)</span>
<span id="cb18-219"><a href="#cb18-219" aria-hidden="true" tabindex="-1"></a>delta_rsquared <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, R2_1, R2_2 <span class="sc">-</span> R2_1, R2_3 <span class="sc">-</span> R2_2, R2_4 <span class="sc">-</span> R2_3)</span>
<span id="cb18-220"><a href="#cb18-220" aria-hidden="true" tabindex="-1"></a>Models <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"Model "</span>, <span class="dv">0</span><span class="sc">:</span><span class="dv">4</span>)</span>
<span id="cb18-221"><a href="#cb18-221" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(delta_rsquared) <span class="ot">&lt;-</span> Models</span>
<span id="cb18-222"><a href="#cb18-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-223"><a href="#cb18-223" aria-hidden="true" tabindex="-1"></a><span class="co"># Tests of R-square change</span></span>
<span id="cb18-224"><a href="#cb18-224" aria-hidden="true" tabindex="-1"></a>model_results <span class="ot">&lt;-</span> knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">cbind</span>(<span class="at">Rsquared =</span> rsquared, </span>
<span id="cb18-225"><a href="#cb18-225" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">Delta.Rsquared =</span> delta_rsquared, </span>
<span id="cb18-226"><a href="#cb18-226" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">anova</span>(<span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  <span class="dv">1</span>), mod1, mod2, mod3, mod4)),</span>
<span id="cb18-227"><a href="#cb18-227" aria-hidden="true" tabindex="-1"></a>                           <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb18-228"><a href="#cb18-228" aria-hidden="true" tabindex="-1"></a>model_results</span>
<span id="cb18-229"><a href="#cb18-229" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-230"><a href="#cb18-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-231"><a href="#cb18-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-232"><a href="#cb18-232" aria-hidden="true" tabindex="-1"></a>Although we didn't have research hypotheses about the individual predictors, it is often useful to report a table such as the one below to summarize that kind of information. The table was produced using the <span class="in">`stargazer`</span> package in R and is representative of the usual format for reporting regression output from hierarchical regression models. The values reported for each variable are  the regression coefficients, with the standard errors in parenthesis. **Please take a  moment to look over the table and write down any questions you have about its interpretation** </span>
<span id="cb18-233"><a href="#cb18-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-234"><a href="#cb18-234" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo = F, fig.align = 'center'}</span></span>
<span id="cb18-235"><a href="#cb18-235" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression Table</span></span>
<span id="cb18-236"><a href="#cb18-236" aria-hidden="true" tabindex="-1"></a><span class="co">#stargazer::stargazer(mod1, mod2, mod3, mod4, type = 'html', omit = "Constant")</span></span>
<span id="cb18-237"><a href="#cb18-237" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"files/images/stargazer.png"</span>)</span>
<span id="cb18-238"><a href="#cb18-238" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-239"><a href="#cb18-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-240"><a href="#cb18-240" aria-hidden="true" tabindex="-1"></a><span class="fu">### Interpretation</span></span>
<span id="cb18-241"><a href="#cb18-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-242"><a href="#cb18-242" aria-hidden="true" tabindex="-1"></a>The focus of this section is on the interpretation of the $\Delta R^2$ statistics and their significance. In practice, we would also interpret the sign and direction of the significant regression coefficients in the final model. As noted above, the outcome variable was log transformed, but we ignore that detail here. It would usually not be necessary to report results both in a table and inline, but the latter are shown for illustrative purposes (practice, practice, practice!).</span>
<span id="cb18-243"><a href="#cb18-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-244"><a href="#cb18-244" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>RQ1: SES had significant linear and quadratic relationships with Reading Achievement. Together, both predictors explained about 17.6% of the variance in Reading Achievement ($R^2 = .176, F(2, 2574) = 275.12, p &lt; .001)$.</span>
<span id="cb18-245"><a href="#cb18-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-246"><a href="#cb18-246" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>RQ2: After controlling for SES, Parental Education explained a small but statistically significant proportion of the variance in Reading Achievement ($\Delta R^2 = .003, F(2, 2572) = 4.94, p = .007$), </span>
<span id="cb18-247"><a href="#cb18-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-248"><a href="#cb18-248" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>RQ3: After controlling for SES and Parental Education, Pre-K status explained an additional .5% of the variation in reading achievement ($\Delta R^2 = .005, F(1, 2571) = 16.15, p &lt; .001$). </span>
<span id="cb18-249"><a href="#cb18-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-250"><a href="#cb18-250" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>RQ4: There was mixed evidence about the interactions between Pre-K Status and the other predictors. The F-test of R-squared change indicated that the interaction terms did not explain a significant amount of variation in reading ($\Delta R^2 = .002, F(4, 2567) = 1.68, p = .15$). However, the interaction with paternal education was significant at the .05 level. After re-running Model 4 with only the paternal education interaction, it was found that this effect was not significant at the .05 level ($t(2570) = -0.856, p = 0.39$; see output below). It may be concluded that there were no significant interactions with Pre-K status. </span>
<span id="cb18-251"><a href="#cb18-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-254"><a href="#cb18-254" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb18-255"><a href="#cb18-255" aria-hidden="true" tabindex="-1"></a>mod4A <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  z_wksesl <span class="sc">+</span> z_wksesl_sq <span class="sc">+</span> z_wkmomed <span class="sc">+</span> z_wkdaded<span class="sc">*</span>p1center)</span>
<span id="cb18-256"><a href="#cb18-256" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod4A)</span>
<span id="cb18-257"><a href="#cb18-257" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-258"><a href="#cb18-258" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb18-259"><a href="#cb18-259" aria-hidden="true" tabindex="-1"></a>In summary, it was found that SES and Parental Education were significant predictors of children's Reading Achievement upon entry to Kindergarten, indicating that pre-existing disparities in reading due to economic factors are apparent at even this very early age. Attendance in Pre-K explained an additional .5% of variance in Reading Achievement and was associated with increased Reading Achievement; however, there was no evidence that participation in Pre-K reduced pre-existing disparities in Reading Achievement associated with the economic factors (i.e., there were no interactions between Pre-K participation and the economic factors).</span>
<span id="cb18-260"><a href="#cb18-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-261"><a href="#cb18-261" aria-hidden="true" tabindex="-1"></a><span class="fu">## Too many predictors? {#sec-too-many-predictors-6}</span></span>
<span id="cb18-262"><a href="#cb18-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-263"><a href="#cb18-263" aria-hidden="true" tabindex="-1"></a>What is better: more predictors or fewer? While there is no definitive answer to this question, there are two points that we should keep in mind when adding predictors into a model:</span>
<span id="cb18-264"><a href="#cb18-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-265"><a href="#cb18-265" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>The ratio of sample size to number of predictors: $N / K$. </span>
<span id="cb18-266"><a href="#cb18-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-267"><a href="#cb18-267" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>The correlation among the predictors (AKA multicollinearity). </span>
<span id="cb18-268"><a href="#cb18-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-269"><a href="#cb18-269" aria-hidden="true" tabindex="-1"></a>In order to understand the effect of these factors in multiple regression, its helpful to refer to the formula for the standard error of a regression coefficient (from @sec-inference-for-coeffecients-3), which is presented again below: </span>
<span id="cb18-270"><a href="#cb18-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-271"><a href="#cb18-271" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb18-272"><a href="#cb18-272" aria-hidden="true" tabindex="-1"></a>SE({b_k}) = \frac{s_Y}{s_k} \sqrt{\frac{1 - R^2}{N - K - 1}} \times \sqrt{\frac{1}{1 - R_k^2}}.</span>
<span id="cb18-273"><a href="#cb18-273" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb18-274"><a href="#cb18-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-275"><a href="#cb18-275" aria-hidden="true" tabindex="-1"></a>Recall that $s$ denotes standard deviations and that $R_k^2$ is the R-squared from the regression of the $k$-th predictor on the remaining $K-1$ predictors. </span>
<span id="cb18-276"><a href="#cb18-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-277"><a href="#cb18-277" aria-hidden="true" tabindex="-1"></a><span class="fu">### $N/K$</span></span>
<span id="cb18-278"><a href="#cb18-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-279"><a href="#cb18-279" aria-hidden="true" tabindex="-1"></a>We can see from the equation for $SE({b_k})$ that increasing the number of predictors leads the term $N-K-1$ to get smaller. Consequently, the ratio</span>
<span id="cb18-280"><a href="#cb18-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-281"><a href="#cb18-281" aria-hidden="true" tabindex="-1"></a>$$ {\frac{1 - R^2}{N - K - 1}} $$ </span>
<span id="cb18-282"><a href="#cb18-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-283"><a href="#cb18-283" aria-hidden="true" tabindex="-1"></a>will get larger (and hence the standard error will get larger) if the increase in the number of predictors is not compensated by an increase in $R^2.$ In other words, predictors that do not add explanatory power to the model (i.e., do not increase R-squared) will lead to reduced precision for all of the regression coefficients. </span>
<span id="cb18-284"><a href="#cb18-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-285"><a href="#cb18-285" aria-hidden="true" tabindex="-1"></a>So long as $N &gt;&gt; K$, the effect of the number of predictors is negligible. But when the number of predictors gets close to the sample size, the estimates of the regression coefficients can become very imprecise. Many seek "rules of thumb" for the ratio of observations to predictors. This is just a complicated way of asking how large the sample size needs to be, and the correct answer to that question is provided by power analysis (@sec-power-2). That said, if $N/K &lt; 30$-ish you should start probably worrying about the number of predictors in your model.</span>
<span id="cb18-286"><a href="#cb18-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-287"><a href="#cb18-287" aria-hidden="true" tabindex="-1"></a><span class="fu">### Multicollinearity </span></span>
<span id="cb18-288"><a href="#cb18-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-289"><a href="#cb18-289" aria-hidden="true" tabindex="-1"></a>Regardless of sample size, when a predictor is highly correlated with the other predictors, its precision is negatively affected via the term $R^2_k$. When $R^2_k = 1$ the situation is called multicollinearity. Note that multicollinearity can occur even if none of the pairwise correlations among the predictors is large -- it has to do with the relation between predictor $k$ and *all* of the other predictors, which is why it is called *multi*collinearity. </span>
<span id="cb18-290"><a href="#cb18-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-291"><a href="#cb18-291" aria-hidden="true" tabindex="-1"></a>The term $1 - R_k^2$ is called the *tolerance* and its reciprocal is called the variance inflation factor (VIF).</span>
<span id="cb18-292"><a href="#cb18-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-293"><a href="#cb18-293" aria-hidden="true" tabindex="-1"></a>$$ VIF = \frac{1}{1 - R_k^2} $$</span>
<span id="cb18-294"><a href="#cb18-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-295"><a href="#cb18-295" aria-hidden="true" tabindex="-1"></a>Note that $\sqrt{VIF}$ appears in formula for the standard error of the regression coefficient. </span>
<span id="cb18-296"><a href="#cb18-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-297"><a href="#cb18-297" aria-hidden="true" tabindex="-1"></a>Some examples of how to interpret the $VIF$ are provided below:</span>
<span id="cb18-298"><a href="#cb18-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-299"><a href="#cb18-299" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>If $VIF = 5$, the estimated regression coefficient is 5 times less precise than it would be without multicollinearity.</span>
<span id="cb18-300"><a href="#cb18-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-301"><a href="#cb18-301" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>If $VIF = 10$, the estimated regression coefficient is 10  times less precise than it would be without multicollinearity.</span>
<span id="cb18-302"><a href="#cb18-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-303"><a href="#cb18-303" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>If $VIF &gt; 10$, it is a good idea to reconsider whether the predictor needs to be recoded  or omitted from the model.</span>
<span id="cb18-304"><a href="#cb18-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-305"><a href="#cb18-305" aria-hidden="true" tabindex="-1"></a>In general, it is a good practice to check VIF as part of model diagnostics, which is the topic of the next chapter. For our example, the VIF statistics for Model 3 and Model 4 are reported below. </span>
<span id="cb18-306"><a href="#cb18-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-307"><a href="#cb18-307" aria-hidden="true" tabindex="-1"></a>For Model 3: </span>
<span id="cb18-310"><a href="#cb18-310" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb18-311"><a href="#cb18-311" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("car")</span></span>
<span id="cb18-312"><a href="#cb18-312" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(mod3)</span>
<span id="cb18-313"><a href="#cb18-313" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-314"><a href="#cb18-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-315"><a href="#cb18-315" aria-hidden="true" tabindex="-1"></a>For Model 4: </span>
<span id="cb18-318"><a href="#cb18-318" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb18-319"><a href="#cb18-319" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(mod4)</span>
<span id="cb18-320"><a href="#cb18-320" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-321"><a href="#cb18-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-322"><a href="#cb18-322" aria-hidden="true" tabindex="-1"></a>We can see that including the interactions led to a high degree of multicollinearity for some of the regression coefficients in the model. Based on this information, as well as the non-significant $\Delta R^2$ for the interaction block, it would be advisable to focus our interpretation on Model 3 rather than Model 4. </span>
<span id="cb18-323"><a href="#cb18-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-324"><a href="#cb18-324" aria-hidden="true" tabindex="-1"></a><span class="fu">## Workbook </span></span>
<span id="cb18-325"><a href="#cb18-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-326"><a href="#cb18-326" aria-hidden="true" tabindex="-1"></a>This section collects the questions asked in this chapter. There aren't many, we will mainly be focussed on going through the worked example during class time. </span>
<span id="cb18-327"><a href="#cb18-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-328"><a href="#cb18-328" aria-hidden="true" tabindex="-1"></a>@sec-hierarchical-models-6</span>
<span id="cb18-329"><a href="#cb18-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-330"><a href="#cb18-330" aria-hidden="true" tabindex="-1"></a>Please take a moment to write down one or more examples of a block of variables from your area of research, and I will invite you to share your examples in class.</span>
<span id="cb18-331"><a href="#cb18-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-332"><a href="#cb18-332" aria-hidden="true" tabindex="-1"></a>@sec-worked-example-6</span>
<span id="cb18-333"><a href="#cb18-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-334"><a href="#cb18-334" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>Look over the tables below and write down any questions you have about their interpretation or the write up provided in @sec-worked-example-6. </span>
<span id="cb18-335"><a href="#cb18-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-336"><a href="#cb18-336" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo = F, fig.align = 'center'}</span></span>
<span id="cb18-337"><a href="#cb18-337" aria-hidden="true" tabindex="-1"></a>model_results</span>
<span id="cb18-338"><a href="#cb18-338" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"files/images/stargazer.png"</span>)</span>
<span id="cb18-339"><a href="#cb18-339" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-340"><a href="#cb18-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-341"><a href="#cb18-341" aria-hidden="true" tabindex="-1"></a><span class="fu">## Exercises </span></span>
<span id="cb18-342"><a href="#cb18-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-343"><a href="#cb18-343" aria-hidden="true" tabindex="-1"></a>The exercises reproduce the worked example in @sec-worked-example-6. We will go through this material in class together, so you don't need to work on it before class (but you can if you want.) </span>
<span id="cb18-344"><a href="#cb18-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-345"><a href="#cb18-345" aria-hidden="true" tabindex="-1"></a>Before staring this section, you may find it useful to scroll to the top of the page, click on the "&lt;/&gt; Code" menu, and select "Show All Code."</span>
<span id="cb18-346"><a href="#cb18-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-347"><a href="#cb18-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-348"><a href="#cb18-348" aria-hidden="true" tabindex="-1"></a>First we set up the variables</span>
<span id="cb18-349"><a href="#cb18-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-352"><a href="#cb18-352" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb18-353"><a href="#cb18-353" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean up env. and load data</span></span>
<span id="cb18-354"><a href="#cb18-354" aria-hidden="true" tabindex="-1"></a><span class="co">#rm(list = ls())</span></span>
<span id="cb18-355"><a href="#cb18-355" aria-hidden="true" tabindex="-1"></a><span class="co">#load("ECLS2577.RData")</span></span>
<span id="cb18-356"><a href="#cb18-356" aria-hidden="true" tabindex="-1"></a><span class="co">#attach(ecls)</span></span>
<span id="cb18-357"><a href="#cb18-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-358"><a href="#cb18-358" aria-hidden="true" tabindex="-1"></a><span class="co"># Recode variables</span></span>
<span id="cb18-359"><a href="#cb18-359" aria-hidden="true" tabindex="-1"></a>p1center <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">-</span> p1center</span>
<span id="cb18-360"><a href="#cb18-360" aria-hidden="true" tabindex="-1"></a>z_c1rrscal <span class="ot">&lt;-</span> <span class="fu">scale</span>(c1rrscal)</span>
<span id="cb18-361"><a href="#cb18-361" aria-hidden="true" tabindex="-1"></a>z_wksesl <span class="ot">&lt;-</span> <span class="fu">scale</span>(wksesl)</span>
<span id="cb18-362"><a href="#cb18-362" aria-hidden="true" tabindex="-1"></a>z_wksesl_sq <span class="ot">&lt;-</span> z_wksesl<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb18-363"><a href="#cb18-363" aria-hidden="true" tabindex="-1"></a>z_wkmomed <span class="ot">&lt;-</span> <span class="fu">scale</span>(wkmomed)</span>
<span id="cb18-364"><a href="#cb18-364" aria-hidden="true" tabindex="-1"></a>z_wkdaded <span class="ot">&lt;-</span> <span class="fu">scale</span>(wkdaded)</span>
<span id="cb18-365"><a href="#cb18-365" aria-hidden="true" tabindex="-1"></a>log_c1rrscal <span class="ot">&lt;-</span> <span class="fu">log</span>(z_c1rrscal <span class="sc">-</span> <span class="fu">min</span>(z_c1rrscal) <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb18-366"><a href="#cb18-366" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-367"><a href="#cb18-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-368"><a href="#cb18-368" aria-hidden="true" tabindex="-1"></a>Next, run the models. </span>
<span id="cb18-369"><a href="#cb18-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-370"><a href="#cb18-370" aria-hidden="true" tabindex="-1"></a><span class="in">```{r results = 'asis'}</span></span>
<span id="cb18-371"><a href="#cb18-371" aria-hidden="true" tabindex="-1"></a><span class="co"># Run models</span></span>
<span id="cb18-372"><a href="#cb18-372" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  z_wksesl <span class="sc">+</span> z_wksesl_sq)</span>
<span id="cb18-373"><a href="#cb18-373" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  z_wksesl <span class="sc">+</span> z_wksesl_sq <span class="sc">+</span> z_wkmomed <span class="sc">+</span> z_wkdaded)</span>
<span id="cb18-374"><a href="#cb18-374" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  z_wksesl <span class="sc">+</span> z_wksesl_sq <span class="sc">+</span> z_wkmomed <span class="sc">+</span> z_wkdaded <span class="sc">+</span> p1center)</span>
<span id="cb18-375"><a href="#cb18-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-376"><a href="#cb18-376" aria-hidden="true" tabindex="-1"></a><span class="co"># Note the syntax here for interacting one variable with many</span></span>
<span id="cb18-377"><a href="#cb18-377" aria-hidden="true" tabindex="-1"></a>mod4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  (z_wksesl <span class="sc">+</span> z_wksesl_sq <span class="sc">+</span> z_wkmomed <span class="sc">+</span> z_wkdaded)<span class="sc">*</span>p1center)</span>
<span id="cb18-378"><a href="#cb18-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-379"><a href="#cb18-379" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression table -- will discuss this in class</span></span>
<span id="cb18-380"><a href="#cb18-380" aria-hidden="true" tabindex="-1"></a><span class="co"># stargazer::stargazer(mod1, mod2, mod3, mod4, type = 'html', omit = "Constant")</span></span>
<span id="cb18-381"><a href="#cb18-381" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"files/images/stargazer.png"</span>)</span>
<span id="cb18-382"><a href="#cb18-382" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-383"><a href="#cb18-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-384"><a href="#cb18-384" aria-hidden="true" tabindex="-1"></a>The <span class="in">`stargazer`</span> table doesn't format nicely in markdown, it is attached as a screen shot instead. We will go through some different types of output with stargazer in class. You must install the <span class="in">`stargazer`</span> package for the code to work. </span>
<span id="cb18-385"><a href="#cb18-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-386"><a href="#cb18-386" aria-hidden="true" tabindex="-1"></a>The above table reports the $R^2$ for each model but does not provide the $\Delta R^2$ statistics or the corresponding F-tests. The $\Delta R^2$ statistics require some additional processing:</span>
<span id="cb18-387"><a href="#cb18-387" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-390"><a href="#cb18-390" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb18-391"><a href="#cb18-391" aria-hidden="true" tabindex="-1"></a><span class="co"># Get R-squared </span></span>
<span id="cb18-392"><a href="#cb18-392" aria-hidden="true" tabindex="-1"></a>R2_1 <span class="ot">&lt;-</span> <span class="fu">summary</span>(mod1)<span class="sc">$</span>r.squared</span>
<span id="cb18-393"><a href="#cb18-393" aria-hidden="true" tabindex="-1"></a>R2_2 <span class="ot">&lt;-</span> <span class="fu">summary</span>(mod2)<span class="sc">$</span>r.squared</span>
<span id="cb18-394"><a href="#cb18-394" aria-hidden="true" tabindex="-1"></a>R2_3 <span class="ot">&lt;-</span> <span class="fu">summary</span>(mod3)<span class="sc">$</span>r.squared</span>
<span id="cb18-395"><a href="#cb18-395" aria-hidden="true" tabindex="-1"></a>R2_4 <span class="ot">&lt;-</span> <span class="fu">summary</span>(mod4)<span class="sc">$</span>r.squared</span>
<span id="cb18-396"><a href="#cb18-396" aria-hidden="true" tabindex="-1"></a>rsquared <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, R2_1, R2_2, R2_3, R2_4)</span>
<span id="cb18-397"><a href="#cb18-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-398"><a href="#cb18-398" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute R-squared change</span></span>
<span id="cb18-399"><a href="#cb18-399" aria-hidden="true" tabindex="-1"></a>delta_rsquared <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, R2_1, R2_2 <span class="sc">-</span> R2_1, R2_3 <span class="sc">-</span> R2_2, R2_4 <span class="sc">-</span> R2_3)</span>
<span id="cb18-400"><a href="#cb18-400" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-401"><a href="#cb18-401" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up for pretty printing</span></span>
<span id="cb18-402"><a href="#cb18-402" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="at">Rsquared =</span> rsquared, </span>
<span id="cb18-403"><a href="#cb18-403" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Delta.Rsquared =</span> delta_rsquared, </span>
<span id="cb18-404"><a href="#cb18-404" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">anova</span>(<span class="fu">lm</span>(log_c1rrscal <span class="sc">~</span>  <span class="dv">1</span>), mod1, mod2, mod3, mod4))</span>
<span id="cb18-405"><a href="#cb18-405" aria-hidden="true" tabindex="-1"></a>             </span>
<span id="cb18-406"><a href="#cb18-406" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(results, <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb18-407"><a href="#cb18-407" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-408"><a href="#cb18-408" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-409"><a href="#cb18-409" aria-hidden="true" tabindex="-1"></a>The variance inflation factors for Model 3 and Model 4 are obtained use the <span class="in">`vif`</span> function of the <span class="in">`car`</span> package (you must install the <span class="in">`car`</span> package for this code to work).</span>
<span id="cb18-410"><a href="#cb18-410" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-413"><a href="#cb18-413" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb18-414"><a href="#cb18-414" aria-hidden="true" tabindex="-1"></a><span class="co"># install.pacakges("car")</span></span>
<span id="cb18-415"><a href="#cb18-415" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(mod3)</span>
<span id="cb18-416"><a href="#cb18-416" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(mod4)</span>
<span id="cb18-417"><a href="#cb18-417" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-418"><a href="#cb18-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-421"><a href="#cb18-421" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb18-422"><a href="#cb18-422" aria-hidden="true" tabindex="-1"></a><span class="co"># clean up</span></span>
<span id="cb18-423"><a href="#cb18-423" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb18-424"><a href="#cb18-424" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(ecls)</span>
<span id="cb18-425"><a href="#cb18-425" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>